version: 2
jobs:
  build:
    docker:
      - image: docker:17.05.0-ce-git
      environment:
        FLASK_CONFIG: testing
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            pip install docker-compose==1.12.0
      - run:
          name: Build application Docker image
          command: |
            docker build -t FILL/sse-member:"$CIRCLE_SHA1" .
      - run:
          name: Run tests
          command: |
            docker run -e FLASK_CONFIG=testing FILL/sse-member:"$CIRCLE_SHA1"
      - deploy:
          name: Push application Docker image
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
              docker tag FILL/sse-member:"$CIRCLE_SHA1" FILL/sse-member:latest;
              docker push FILL/sse-member:"$CIRCLE_SHA1";
              docker push FILL/sse-member:latest;
            fi
